### ISSUE TITLE
While hitting token api got CORS error

### ISSUE THREAD

**Issue by meganathan-codenatives** [HL7-DaVinci/crd-request-generator#37]
http://localhost:8180/auth/realms/ClientFhirServer/protocol/openid-connect/token

grant_type=password&username=FHIR&password=EpicFhir11!&client_id=app-login

![image](https://user-images.githubusercontent.com/69626182/113717607-68949580-9709-11eb-8732-bc3043a0d5be.png)

**Comment by KeeyanGhoreshi** [comment]
It's likely that this isn't a CORS error, but something else.  You can check the logs of the auth server to see a more accurate error message.
